### PR TITLE
WIP: Build Lemon Tree Map

### PR DESCRIPTION
**Pull request by danielwrobert**
This is for the lemon tree map functionality. Starting with the Google Maps API and planning to experiment with the MarkerCluster feature as a starting point.

To address the concern of specific locations (people's houses) being added to the map, I am thinking about adding a lat/long center point area for each neighborhood and allowing the map points to get populated there, based on the neighborhood they're attached to.

### CODE REVIEW

**Comment by sarahmonster** [comment]
I was thinking we wouldn't use map markers at all, since we don't want to show the exact addresses or have it seem as though we're exposing the addresses.

What I was thinking instead was to adjust the shading of the neighbourhood boundaries, so they'd be coloured darker if there are more trees registered there. (This is what the current map does/did, but the neighbourhood boundaries were too small and the colours were all the exact same.)

Ideally, when you hover/click on the neighbourhood boundary, it would highlight (probably a darker border) and show the name of the neighbourhood + the number of trees registered there.

I *think* this is a simpler solution than the marker clusters approach, and it's the plan I outlined to Isabel originally. Most of this is pretty achievable via CSS, we'd just need to sort out the actual drawing of the neighbourhood polygon boundaries themselves.

**Comment by danielwrobert** [comment]
> I think this is a simpler solution than the marker clusters approach
I'm not sure if it is or not but it sounds worth looking into. The marker clusters isn't really that complicated either. I was going to dynamically add pins to the map based on the neighborhood - I was thinking to choose a center point for each neighborhood to populate the pins around so that we're not exposing any actual addresses. I already have the data set up to get the info I need for this route.

That said, it _may_ be easier to adjust the shading, as you mentioned. Also, less functionality to worry if it can be achieved via CSS. I like that idea and I think it's definitely worth exploring - I'll dig into that route next. Thanks, @sarahmonster!

**Comment by danielwrobert** [comment]
I added lemon markers with the lemon tree count to the Just One Tree map.

To set the marker points, I created Lat and Lng custom fields in the Neighborhoods taxonomy.

That way, we can set a center point for each neighborhood and have the map markers all render there - which should solve the problem of not wanting exact marker locations shown.

I only set the center Lat & Lng for Chinatown, Haight-Ashbury, and Fishermans Warf to test.

If we end up taking this approach, we'll want to set those points for all of the items. Alternatively, I could also set that data in the JS and remove those custom fields. Whichever is easier.

screenshot 2017-03-20 16 24 06

I took this approach, initially, because it ended up being _much_ more straightforward to implement than the aforementioned map-neighborhood-coloring approach. I wanted to get _something_ working because I know the deadline is coming up soon. I have branched off of this to explore the map-coloring implementation [here](https://github.com/a8cteam51/just-one-tree/tree/update/tree-map-color-areas).

**Comment by danielwrobert** [comment]
Closing this PR out in favor of #79.

**Pull request closed without merging**
