### PR TITLE
WIP: Add map of orchards

### PR DESCRIPTION
**Pull request by sarahmonster**
So far I have the Google map set up, and I've got a geocoder working to locate the entered addresses. The markers don't seem to be showing up though, and I'm not sure why. No console errors. @danielwrobert could you have a quick gander and tell me what I'm doing wrong?

### CODE REVIEW

**Comment by danielwrobert** [comment]
I just tested and I am seeing the markers showing up as expected.

screenshot 2017-04-12 21 57 25

**Comment by sarahmonster** [comment]
What data does that correspond to? Mine don't show up at all. :(

screenshot 2017-04-13 11 34 07

**Comment by danielwrobert** [comment]
It corresponds to the Orchards CPT. Based on your code, it looks like it requires an address for the marker http request. I'm assuming it needs to be a legitimate address for that to work, otherwise the you won't get valid data for the marker point.

screenshot 2017-04-13 08 01 36

Note that the Neighborhood meta data doesn't seem to matter. I tested checking and unchecking North Beach and both worked. I'm not sure if that's being used elsewhere for the orchards but, if not, maybe it can be removed?

**Comment by sarahmonster** [comment]
> It corresponds to the Orchards CPT. Based on your code, it looks like it requires an address for the marker http request. I'm assuming it needs to be a legitimate address for that to work, otherwise the you won't get valid data for the marker point.

I meant what user-entered data. 😄 I entered some garbage/empty data for testing, and I'm wondering if that's what caused the conflict. I'd like it if the JS could handle/ignore garbage data, since I suspect it's possible that may get entered at some point, but I'm not sure quite how to account for that—I thought I already was. 😭

> Note that the Neighborhood meta data doesn't seem to matter. I tested checking and unchecking North Beach and both worked. I'm not sure if that's being used elsewhere for the orchards but, if not, maybe it can be removed?

Yeah, I actually think just a single line for the address would be better, but I wasn't sure what Isabel would want to enter. I may update this—I think entering the address as a single line might be more straightforward from a user perspective.

**Pull request merged**
