### PR TITLE
Automate tree count

### LINKED ISSUE #68: Tree-o-meter numbers should update automatically
I set up the CPT in #50 for registered trees, so we should be able to count the total number of registered tree automatically. 

A few things to note:
- counting entries alone won't do the trick, since a single entry can have multiple trees (see the "number of trees" field)
- we'll probably still want to keep the theme option for goal number of trees, so that can be adjusted if needed
- we'll need to import existing registration data in order for the count to be accurate (#67)
- it would be nice if we can cache this number, rather than re-running the calculations every time (probably a [transient](https://css-tricks.com/the-deal-with-wordpress-transients/)?)

### PR DESCRIPTION
**Pull request by sarahmonster**
This removes the theme mod for the tree count and instead generates the tree count automatically by adding up all the tree count numbers in the tree taxonomy. (See #50 for setup.) 

Note that each "tree" post can represent a number of trees since people submit once but enter the number of trees they own, so we're adding up the numbers entered into this field rather than just counting all the trees posts.

Fixes #68.

I think this is the best way of going about this, but I'd appreciate a quick sanity-check by anyone who knows more about transients and/or caching than I do, since this is super outside my ballpark. I've saved the number in a transient to reduce server stress, since I anticipate having a relatively high number of tree registrations. 

The transient expires every hour, but I should probably adjust that so it's every 12 hours. I wonder if it'd be better to have the transient never expire, and just update the count when a new tree post is published, deleted, or edited, if there's a sensible way of doing that instead. (Maybe better to evaluate later, once we've sorted out #67 and can see how it manages with the existing data...)

### CODE REVIEW

**Comment by sarahmonster** [comment]
The tree registrations definitely won't come in that frequently (particularly since they'll only be drafts until Isabel publishes them) so twelve hours may actually be more generous than is strictly required—mostly I'd just like to avoid Isabel getting super confused if the count isn't exactly as expected. The most elegant solution would be to update the count when a new tree post is published (or an existing one is edited, potentially) but I'm not entirely sure how/if that would work.

**Comment by sarahmonster** [comment]
FYI so far (with ~1000 posts) it doesn't seem to be breaking anything:

screenshot 2017-02-22 16 04 32

**Comment by sarahmonster** [comment]
That might be handy. I think the biggest use case here would really be when a new post is published (does that count as it being updated?) If you have an example, I could probably work it in.

**Comment by danielwrobert** [comment]
Yes, I believe that counts in my idea. You essentially hook into the `save_post` action, flush your transients, and set a new one. It would be pretty easy to work in and shouldn't really interfere with what you currently have. I'll link you to an example in our channel. Ping me over there! :)

**Comment by sarahmonster** [comment]
Bleegghhghghghg so I added a variant of the function and it... sorta works? It seems to update the transient but only after I save the updated post twice? I'm confused.

**Comment by danielwrobert** [comment]
Tested out and the latest update we discussed in the channel seems to be working for me.

I'm going to merge this in now! :)

**Pull request merged**
